const Types = {
  TEST: 'TEST',
  SAVEDEBUG: 'SAVEDEBUG',
  SAVE_USER_TOKEN: 'SAVE_USER_TOKEN',
  SAVE_USER: 'SAVE_USER',
  SET_APP_OPEN: 'SET_APP_OPEN',
  NETWORK_STATUS: 'NETWORK_STATUS',
  SHOW_LOADING: 'SHOW_LOADING',
  SET_LOADING: 'SET_LOADING',
  RECENT_SEARCH: 'RECENT_SEARCH',
  SET_OVERVIEW: 'SET_OVERVIEW',
  SAVE_COURSE: 'SAVE_COURSE',
  SAVE_WISHLIST: 'SAVE_WISHLIST',
  SAVE_PRODUCT_IAP: 'SAVE_PRODUCT_IAP',
  SET_FCM_TOKEN: 'SET_FCM_TOKEN',
  SAVE_NOTIFICATIONS: 'SAVE_NOTIFICATIONS',
  SET_TIME_SHOW_POPUP: 'SET_TIME_SHOW_POPUP',
  SET_ENABLE_NOTIFICATIONS: 'SET_ENABLE_NOTIFICATIONS',
  SET_LAST_ID_NOTIFICATIONS: 'SET_LAST_ID_NOTIFICATIONS',
  RESET_NOTIFICATIONS: 'RESET_NOTIFICATIONS',
  SAVE_LANGUAGE: 'SAVE_LANGUAGE',
};

export default Types;
